### ISSUE TITLE
'./gradlew :SDL2:distributeLib' : Exception thrown while executing model rule

### ISSUE THREAD

**Issue by holdengreen** [stephen47/android-sdl2-gradle-template#2]
This is the output while executing './gradlew :SDL2:distributeLib'

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':SDL2'.
> Exception thrown while executing model rule: NdkComponentModelPlugin.Rules#createNativeLibrary(ModelMap<NativeLibrarySpec>, NdkConfig, NdkHandler, ModelMap<FunctionalSourceSet>, File, ServiceRegistry) > create(SDL2)
   > java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by stephen47** [comment]
Unfortunately, I've been out of touch with Android development since I created this repo and it looks like the build tools have changed. I had a quick look and can reproduce the issue but I'm not sure how to resolve. I might suggest following this tutorial (it's what I used as a basis, and looks like it was updated after I created this repo):

https://lazyfoo.net/tutorials/SDL/52_hello_mobile/index.php

Sorry I could be more help.
